/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package geoecho.view;

import com.teamdev.jxmaps.MapViewOptions;
import java.awt.Color;
import java.awt.Frame;
import java.awt.Toolkit;

/**
 *
 * @author BlueStorm
 */
public class GUIForm extends javax.swing.JFrame {

    /**
     * Creates new form Gui
     */
    public GUIForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        MapViewOptions options = new MapViewOptions();
        options.importPlaces();
        jPanelInf.add(new MapPanel(options));
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLateral = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelTop = new javax.swing.JPanel();
        jLabelIconoCerrar = new javax.swing.JLabel();
        jLabelIconoMinimizar = new javax.swing.JLabel();
        jPanelSup = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jPanelInf = new javax.swing.JPanel();
        jPanelLateral1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanelLateral2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanelLateral3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanelLateral4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GeoEcho");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/res/icon.png")));
        setLocation(new java.awt.Point(0, 0));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelLateral.setBackground(new java.awt.Color(33, 33, 33));
        jPanelLateral.setName("lateral"); // NOI18N
        jPanelLateral.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanelLateral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelLateralMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelLateralMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelLateralMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanelLateralMouseReleased(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/map-marker.png"))); // NOI18N

        javax.swing.GroupLayout jPanelLateralLayout = new javax.swing.GroupLayout(jPanelLateral);
        jPanelLateral.setLayout(jPanelLateralLayout);
        jPanelLateralLayout.setHorizontalGroup(
            jPanelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLateralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelLateralLayout.setVerticalGroup(
            jPanelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLateralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanelLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        jPanelTop.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTop.setName("barraSuperior"); // NOI18N
        jPanelTop.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelTopMouseDragged(evt);
            }
        });
        jPanelTop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelTopMousePressed(evt);
            }
        });

        jLabelIconoCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/close.png"))); // NOI18N
        jLabelIconoCerrar.setName("labelCerrar"); // NOI18N
        jLabelIconoCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIconoCerrarMouseClicked(evt);
            }
        });

        jLabelIconoMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/minimize.png"))); // NOI18N
        jLabelIconoMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIconoMinimizarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelTopLayout = new javax.swing.GroupLayout(jPanelTop);
        jPanelTop.setLayout(jPanelTopLayout);
        jPanelTopLayout.setHorizontalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTopLayout.createSequentialGroup()
                .addContainerGap(686, Short.MAX_VALUE)
                .addComponent(jLabelIconoMinimizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelIconoCerrar)
                .addContainerGap())
        );
        jPanelTopLayout.setVerticalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelIconoCerrar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelIconoMinimizar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(22, 22, 22))
        );

        getContentPane().add(jPanelTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 750, 30));

        jPanelSup.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSup.setName("panelSuperior"); // NOI18N

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelTitulo.setText("Admin Tools");

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanelSupLayout = new javax.swing.GroupLayout(jPanelSup);
        jPanelSup.setLayout(jPanelSupLayout);
        jPanelSupLayout.setHorizontalGroup(
            jPanelSupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSupLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanelSupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitulo)
                    .addComponent(jLabelLogo))
                .addContainerGap(546, Short.MAX_VALUE))
        );
        jPanelSupLayout.setVerticalGroup(
            jPanelSupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSupLayout.createSequentialGroup()
                .addComponent(jLabelLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jLabelTitulo)
                .addContainerGap())
        );

        getContentPane().add(jPanelSup, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 750, 120));

        jPanelInf.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanelInf, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 750, 450));

        jPanelLateral1.setBackground(new java.awt.Color(33, 33, 33));
        jPanelLateral1.setName("lateral"); // NOI18N
        jPanelLateral1.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanelLateral1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelLateralMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelLateralMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelLateralMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanelLateralMouseReleased(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/account.png"))); // NOI18N

        javax.swing.GroupLayout jPanelLateral1Layout = new javax.swing.GroupLayout(jPanelLateral1);
        jPanelLateral1.setLayout(jPanelLateral1Layout);
        jPanelLateral1Layout.setHorizontalGroup(
            jPanelLateral1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLateral1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelLateral1Layout.setVerticalGroup(
            jPanelLateral1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLateral1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanelLateral1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanelLateral2.setBackground(new java.awt.Color(33, 33, 33));
        jPanelLateral2.setName("lateral"); // NOI18N
        jPanelLateral2.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanelLateral2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelLateralMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelLateralMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelLateralMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanelLateralMouseReleased(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/web.png"))); // NOI18N

        javax.swing.GroupLayout jPanelLateral2Layout = new javax.swing.GroupLayout(jPanelLateral2);
        jPanelLateral2.setLayout(jPanelLateral2Layout);
        jPanelLateral2Layout.setHorizontalGroup(
            jPanelLateral2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLateral2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelLateral2Layout.setVerticalGroup(
            jPanelLateral2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLateral2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanelLateral2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        jPanelLateral3.setBackground(new java.awt.Color(33, 33, 33));
        jPanelLateral3.setName("lateral"); // NOI18N
        jPanelLateral3.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanelLateral3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelLateralMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelLateralMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelLateralMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanelLateralMouseReleased(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/wrench.png"))); // NOI18N

        javax.swing.GroupLayout jPanelLateral3Layout = new javax.swing.GroupLayout(jPanelLateral3);
        jPanelLateral3.setLayout(jPanelLateral3Layout);
        jPanelLateral3Layout.setHorizontalGroup(
            jPanelLateral3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLateral3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelLateral3Layout.setVerticalGroup(
            jPanelLateral3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLateral3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanelLateral3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        jPanelLateral4.setBackground(new java.awt.Color(33, 33, 33));
        jPanelLateral4.setName("lateral"); // NOI18N
        jPanelLateral4.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanelLateral4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelLateralMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelLateralMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelLateralMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanelLateralMouseReleased(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/finance.png"))); // NOI18N

        javax.swing.GroupLayout jPanelLateral4Layout = new javax.swing.GroupLayout(jPanelLateral4);
        jPanelLateral4.setLayout(jPanelLateral4Layout);
        jPanelLateral4Layout.setHorizontalGroup(
            jPanelLateral4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLateral4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelLateral4Layout.setVerticalGroup(
            jPanelLateral4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLateral4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanelLateral4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        jPanel1.setBackground(new java.awt.Color(33, 33, 33));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 50, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents
private int x;
    private int y;
    private void jPanelTopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTopMousePressed
        // Reiniciar la posicion x y al hacer click
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanelTopMousePressed

    private void jPanelTopMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTopMouseDragged
        // actualiza x y al hacer arrastrar
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_jPanelTopMouseDragged

    private void jLabelIconoCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoCerrarMouseClicked
        // Cierra la app
        System.exit(0);
    }//GEN-LAST:event_jLabelIconoCerrarMouseClicked

    private void jLabelIconoMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoMinimizarMouseClicked
        // Minimiza la app
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jLabelIconoMinimizarMouseClicked

    private void jPanelLateralMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLateralMouseEntered
        evt.getComponent().setBackground(new java.awt.Color(55, 55, 55));
    }//GEN-LAST:event_jPanelLateralMouseEntered

    private void jPanelLateralMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLateralMouseExited
        evt.getComponent().setBackground(new java.awt.Color(33, 33, 33));
    }//GEN-LAST:event_jPanelLateralMouseExited

    private void jPanelLateralMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLateralMousePressed
        evt.getComponent().setBackground(new java.awt.Color(77, 77, 77));
    }//GEN-LAST:event_jPanelLateralMousePressed

    private void jPanelLateralMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLateralMouseReleased
        evt.getComponent().setBackground(new java.awt.Color(55, 55, 55));
    }//GEN-LAST:event_jPanelLateralMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelIconoCerrar;
    private javax.swing.JLabel jLabelIconoMinimizar;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelInf;
    private javax.swing.JPanel jPanelLateral;
    private javax.swing.JPanel jPanelLateral1;
    private javax.swing.JPanel jPanelLateral2;
    private javax.swing.JPanel jPanelLateral3;
    private javax.swing.JPanel jPanelLateral4;
    private javax.swing.JPanel jPanelSup;
    private javax.swing.JPanel jPanelTop;
    // End of variables declaration//GEN-END:variables
}
