/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package geoecho.view;

import static helpers.Constants.*;
import java.awt.Frame;
import java.awt.Toolkit;
import javax.swing.JPanel;

/**
 *
 * @author BlueStorm
 */
public class GUIForm extends javax.swing.JFrame {

    /**
     * Creates new form Gui
     */
    public GUIForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTop = new javax.swing.JPanel();
        jLabelIconoCerrar = new javax.swing.JLabel();
        jLabelIconoMinimizar = new javax.swing.JLabel();
        jPanelSup = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jPanelBPolyLine = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelBUser = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanelBWorld = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanelBConfig = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanelBStatistic = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanelLateral = new javax.swing.JPanel();
        jPanelBMarker = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLayeredPane = new javax.swing.JLayeredPane();
        jPanelSplash = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanelConfig = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelUserInfo = new javax.swing.JPanel();
        jPanelUserInfo.setVisible(false);
        jToggleButtonBanUser = new javax.swing.JToggleButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabelUserInfoName = new javax.swing.JLabel();
        jLabelUserInfoEmail = new javax.swing.JLabel();
        jLabelUserInfoType = new javax.swing.JLabel();
        jLabelUserInfoTotalMessages = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaUserMessages = new javax.swing.JTextArea();
        jLabelPic1 = new javax.swing.JLabel();
        jLabelPic2 = new javax.swing.JLabel();
        jLabelPic3 = new javax.swing.JLabel();
        jLabelPic4 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jButtonSearchUser = new javax.swing.JButton();
        jTextFieldSearchUser = new javax.swing.JTextField();
        jLabelSearch = new javax.swing.JLabel();
        jLabelUserServerInfo = new javax.swing.JLabel();
        jPanelWorld = new javax.swing.JPanel();
        jPanelStadistics = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabelTotalUserStatistics = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabelTotalMessageStatistics = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanelMarker = new javax.swing.JPanel();
        jPanelPolyline = new javax.swing.JPanel();
        jLabelPolyInfoServer = new javax.swing.JLabel();
        jButtonPolySearch = new javax.swing.JButton();
        jTextFieldPoly = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jPanelPolyLineMap = new javax.swing.JPanel();
        jPanelUser = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButtonLogout = new javax.swing.JButton();
        jlabelUser = new javax.swing.JLabel();
        jLabelmail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GeoEcho");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/res/icon.png")));
        setLocation(new java.awt.Point(0, 0));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelTop.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTop.setName("barraSuperior"); // NOI18N
        jPanelTop.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelTopMouseDragged(evt);
            }
        });
        jPanelTop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelTopMousePressed(evt);
            }
        });

        jLabelIconoCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/close.png"))); // NOI18N
        jLabelIconoCerrar.setName("labelCerrar"); // NOI18N
        jLabelIconoCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelIconoCerrarMouseReleased(evt);
            }
        });

        jLabelIconoMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/minimize.png"))); // NOI18N
        jLabelIconoMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelIconoMinimizarMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelTopLayout = new javax.swing.GroupLayout(jPanelTop);
        jPanelTop.setLayout(jPanelTopLayout);
        jPanelTopLayout.setHorizontalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTopLayout.createSequentialGroup()
                .addContainerGap(686, Short.MAX_VALUE)
                .addComponent(jLabelIconoMinimizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelIconoCerrar)
                .addContainerGap())
        );
        jPanelTopLayout.setVerticalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelIconoCerrar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelIconoMinimizar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(22, 22, 22))
        );

        getContentPane().add(jPanelTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 750, 30));

        jPanelSup.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSup.setName("panelSuperior"); // NOI18N

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelTitulo.setText("     ");

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanelSupLayout = new javax.swing.GroupLayout(jPanelSup);
        jPanelSup.setLayout(jPanelSupLayout);
        jPanelSupLayout.setHorizontalGroup(
            jPanelSupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSupLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanelSupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitulo)
                    .addComponent(jLabelLogo))
                .addContainerGap(546, Short.MAX_VALUE))
        );
        jPanelSupLayout.setVerticalGroup(
            jPanelSupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSupLayout.createSequentialGroup()
                .addComponent(jLabelLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jLabelTitulo)
                .addContainerGap())
        );

        getContentPane().add(jPanelSup, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 750, 120));

        jPanelBPolyLine.setBackground(new java.awt.Color(33, 33, 33));
        jPanelBPolyLine.setName("lateral"); // NOI18N
        jPanelBPolyLine.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanelBPolyLine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelBMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelBMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanelMouseReleased(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/polyline.png"))); // NOI18N

        javax.swing.GroupLayout jPanelBPolyLineLayout = new javax.swing.GroupLayout(jPanelBPolyLine);
        jPanelBPolyLine.setLayout(jPanelBPolyLineLayout);
        jPanelBPolyLineLayout.setHorizontalGroup(
            jPanelBPolyLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBPolyLineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelBPolyLineLayout.setVerticalGroup(
            jPanelBPolyLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBPolyLineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanelBPolyLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, -1));

        jPanelBUser.setBackground(new java.awt.Color(33, 33, 33));
        jPanelBUser.setName("lateral"); // NOI18N
        jPanelBUser.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanelBUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelBMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelBMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanelMouseReleased(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/account.png"))); // NOI18N

        javax.swing.GroupLayout jPanelBUserLayout = new javax.swing.GroupLayout(jPanelBUser);
        jPanelBUser.setLayout(jPanelBUserLayout);
        jPanelBUserLayout.setHorizontalGroup(
            jPanelBUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelBUserLayout.setVerticalGroup(
            jPanelBUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanelBUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanelBWorld.setBackground(new java.awt.Color(33, 33, 33));
        jPanelBWorld.setName("lateral"); // NOI18N
        jPanelBWorld.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanelBWorld.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelBMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelBMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanelMouseReleased(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/web.png"))); // NOI18N

        javax.swing.GroupLayout jPanelBWorldLayout = new javax.swing.GroupLayout(jPanelBWorld);
        jPanelBWorld.setLayout(jPanelBWorldLayout);
        jPanelBWorldLayout.setHorizontalGroup(
            jPanelBWorldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBWorldLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelBWorldLayout.setVerticalGroup(
            jPanelBWorldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBWorldLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanelBWorld, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        jPanelBConfig.setBackground(new java.awt.Color(33, 33, 33));
        jPanelBConfig.setName("lateral"); // NOI18N
        jPanelBConfig.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanelBConfig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelBMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelBMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanelMouseReleased(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/wrench.png"))); // NOI18N

        javax.swing.GroupLayout jPanelBConfigLayout = new javax.swing.GroupLayout(jPanelBConfig);
        jPanelBConfig.setLayout(jPanelBConfigLayout);
        jPanelBConfigLayout.setHorizontalGroup(
            jPanelBConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBConfigLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelBConfigLayout.setVerticalGroup(
            jPanelBConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBConfigLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanelBConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        jPanelBStatistic.setBackground(new java.awt.Color(33, 33, 33));
        jPanelBStatistic.setName("lateral"); // NOI18N
        jPanelBStatistic.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanelBStatistic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelBMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelBMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanelMouseReleased(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/finance.png"))); // NOI18N

        javax.swing.GroupLayout jPanelBStatisticLayout = new javax.swing.GroupLayout(jPanelBStatistic);
        jPanelBStatistic.setLayout(jPanelBStatisticLayout);
        jPanelBStatisticLayout.setHorizontalGroup(
            jPanelBStatisticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBStatisticLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelBStatisticLayout.setVerticalGroup(
            jPanelBStatisticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBStatisticLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanelBStatistic, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        jPanelLateral.setBackground(new java.awt.Color(33, 33, 33));

        javax.swing.GroupLayout jPanelLateralLayout = new javax.swing.GroupLayout(jPanelLateral);
        jPanelLateral.setLayout(jPanelLateralLayout);
        jPanelLateralLayout.setHorizontalGroup(
            jPanelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanelLateralLayout.setVerticalGroup(
            jPanelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 50, 300));

        jPanelBMarker.setBackground(new java.awt.Color(33, 33, 33));
        jPanelBMarker.setName("lateral"); // NOI18N
        jPanelBMarker.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanelBMarker.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelBMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelBMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanelMouseReleased(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/map-marker.png"))); // NOI18N

        javax.swing.GroupLayout jPanelBMarkerLayout = new javax.swing.GroupLayout(jPanelBMarker);
        jPanelBMarker.setLayout(jPanelBMarkerLayout);
        jPanelBMarkerLayout.setHorizontalGroup(
            jPanelBMarkerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBMarkerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelBMarkerLayout.setVerticalGroup(
            jPanelBMarkerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBMarkerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanelBMarker, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        jLayeredPane.setPreferredSize(new java.awt.Dimension(750, 450));

        jPanelSplash.setPreferredSize(new java.awt.Dimension(750, 450));
        jPanelSplash.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(33, 33, 33));
        jLabel9.setText("Welcome to GeoEcho");
        jPanelSplash.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(33, 33, 33));
        jLabel10.setText("Administrative Tools");
        jPanelSplash.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/world-512.png"))); // NOI18N
        jPanelSplash.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, -1));

        jPanelConfig.setPreferredSize(new java.awt.Dimension(750, 450));
        jPanelConfig.setVisible(false);
        jPanelConfig.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanelConfig.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 750, 10));

        jPanelUserInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToggleButtonBanUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jToggleButtonBanUser.setForeground(new java.awt.Color(255, 51, 51));
        jToggleButtonBanUser.setText("BAN USER");
        jPanelUserInfo.add(jToggleButtonBanUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 330, -1, -1));
        jPanelUserInfo.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 319, 752, 10));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("User name:");
        jPanelUserInfo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 11, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Registered E-mail:");
        jPanelUserInfo.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 11, -1, 14));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("User Type:");
        jPanelUserInfo.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 34, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Total Messages:");
        jPanelUserInfo.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 34, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Last Messages:");
        jPanelUserInfo.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 69, -1, -1));

        jLabelUserInfoName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelUserInfoName.setText(" ");
        jLabelUserInfoName.setToolTipText("");
        jPanelUserInfo.add(jLabelUserInfoName, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 11, 210, -1));

        jLabelUserInfoEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelUserInfoEmail.setText(" ");
        jLabelUserInfoEmail.setToolTipText("");
        jPanelUserInfo.add(jLabelUserInfoEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 11, 250, -1));

        jLabelUserInfoType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelUserInfoType.setText(" ");
        jLabelUserInfoType.setToolTipText("");
        jPanelUserInfo.add(jLabelUserInfoType, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 34, 210, -1));

        jLabelUserInfoTotalMessages.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelUserInfoTotalMessages.setText(" ");
        jLabelUserInfoTotalMessages.setToolTipText("");
        jPanelUserInfo.add(jLabelUserInfoTotalMessages, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 34, 250, -1));

        jTextAreaUserMessages.setColumns(20);
        jTextAreaUserMessages.setRows(5);
        jScrollPane1.setViewportView(jTextAreaUserMessages);

        jPanelUserInfo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 92, 314, 210));

        jLabelPic1.setMaximumSize(new java.awt.Dimension(184, 100));
        jPanelUserInfo.add(jLabelPic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 92, 188, 104));

        jLabelPic2.setMaximumSize(new java.awt.Dimension(184, 100));
        jPanelUserInfo.add(jLabelPic2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 92, 188, 104));

        jLabelPic3.setMaximumSize(new java.awt.Dimension(184, 100));
        jPanelUserInfo.add(jLabelPic3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 198, 188, 104));

        jLabelPic4.setMaximumSize(new java.awt.Dimension(184, 100));
        jPanelUserInfo.add(jLabelPic4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 198, 188, 104));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Last Pictures:");
        jPanelUserInfo.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 69, -1, -1));

        jPanelConfig.add(jPanelUserInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, 360));

        jButtonSearchUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonSearchUser.setText("Search");
        jPanelConfig.add(jButtonSearchUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, -1, -1));

        jTextFieldSearchUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldSearchUser.setText("User");
        jPanelConfig.add(jTextFieldSearchUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 126, -1));
        jPanelConfig.add(jLabelSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 17, 141, -1));

        jLabelUserServerInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelUserServerInfo.setText(" ");
        jPanelConfig.add(jLabelUserServerInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 206, -1));

        jPanelWorld.setPreferredSize(new java.awt.Dimension(750, 450));
        jPanelWorld.setLayout(new java.awt.BorderLayout());

        jPanelStadistics.setPreferredSize(new java.awt.Dimension(750, 450));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Total Users:");

        jLabelTotalUserStatistics.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelTotalUserStatistics.setText("0");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Total Active Users (last 24h):");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel16.setText("0");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Total Messages:");

        jLabelTotalMessageStatistics.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelTotalMessageStatistics.setText("0");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Total Messages (last 24h):");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel20.setText("0");

        javax.swing.GroupLayout jPanelStadisticsLayout = new javax.swing.GroupLayout(jPanelStadistics);
        jPanelStadistics.setLayout(jPanelStadisticsLayout);
        jPanelStadisticsLayout.setHorizontalGroup(
            jPanelStadisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelStadisticsLayout.createSequentialGroup()
                .addGroup(jPanelStadisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelStadisticsLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabelTotalUserStatistics))
                    .addGroup(jPanelStadisticsLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel16))
                    .addGroup(jPanelStadisticsLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel15))
                    .addGroup(jPanelStadisticsLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 271, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelStadisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelStadisticsLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel17)
                        .addGap(132, 132, 132))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelStadisticsLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelStadisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelStadisticsLayout.createSequentialGroup()
                                .addComponent(jLabelTotalMessageStatistics)
                                .addGap(162, 162, 162))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelStadisticsLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(153, 153, 153))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelStadisticsLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(93, 93, 93))))))
        );
        jPanelStadisticsLayout.setVerticalGroup(
            jPanelStadisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(jPanelStadisticsLayout.createSequentialGroup()
                .addGroup(jPanelStadisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelStadisticsLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelTotalUserStatistics)
                        .addGap(118, 118, 118)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16))
                    .addGroup(jPanelStadisticsLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelTotalMessageStatistics)
                        .addGap(117, 117, 117)
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20)))
                .addContainerGap(214, Short.MAX_VALUE))
        );

        jPanelMarker.setPreferredSize(new java.awt.Dimension(750, 450));
        jPanelMarker.setLayout(new java.awt.BorderLayout());

        jPanelPolyline.setPreferredSize(new java.awt.Dimension(750, 450));
        jPanelPolyline.setVisible(false);

        jLabelPolyInfoServer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPolyInfoServer.setText(" ");

        jButtonPolySearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonPolySearch.setText("Search");
        jButtonPolySearch.setToolTipText("");

        jTextFieldPoly.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldPoly.setText("User");

        jPanelPolyLineMap.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanelPolylineLayout = new javax.swing.GroupLayout(jPanelPolyline);
        jPanelPolyline.setLayout(jPanelPolylineLayout);
        jPanelPolylineLayout.setHorizontalGroup(
            jPanelPolylineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPolylineLayout.createSequentialGroup()
                .addContainerGap(365, Short.MAX_VALUE)
                .addComponent(jLabelPolyInfoServer, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPoly, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPolySearch)
                .addContainerGap())
            .addComponent(jSeparator4)
            .addComponent(jPanelPolyLineMap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelPolylineLayout.setVerticalGroup(
            jPanelPolylineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPolylineLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelPolylineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPolyInfoServer)
                    .addComponent(jButtonPolySearch)
                    .addComponent(jTextFieldPoly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelPolyLineMap, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelUser.setVisible(false);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("User Name:");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("E-Mail:");

        jButtonLogout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonLogout.setText("Logout");

        jlabelUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabelmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanelUserLayout = new javax.swing.GroupLayout(jPanelUser);
        jPanelUser.setLayout(jPanelUserLayout);
        jPanelUserLayout.setHorizontalGroup(
            jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUserLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addGap(58, 58, 58)
                .addGroup(jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelmail, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addComponent(jlabelUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(347, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUserLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonLogout)
                .addGap(57, 57, 57))
        );
        jPanelUserLayout.setVerticalGroup(
            jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUserLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jlabelUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabelmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 262, Short.MAX_VALUE)
                .addComponent(jButtonLogout)
                .addGap(66, 66, 66))
        );

        jLayeredPane.setLayer(jPanelSplash, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane.setLayer(jPanelConfig, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane.setLayer(jPanelWorld, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane.setLayer(jPanelStadistics, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane.setLayer(jPanelMarker, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane.setLayer(jPanelPolyline, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane.setLayer(jPanelUser, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPaneLayout = new javax.swing.GroupLayout(jLayeredPane);
        jLayeredPane.setLayout(jLayeredPaneLayout);
        jLayeredPaneLayout.setHorizontalGroup(
            jLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelConfig, javax.swing.GroupLayout.DEFAULT_SIZE, 852, Short.MAX_VALUE)
            .addGroup(jLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelSplash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelWorld, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelStadistics, javax.swing.GroupLayout.DEFAULT_SIZE, 852, Short.MAX_VALUE))
            .addGroup(jLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelMarker, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelPolyline, javax.swing.GroupLayout.DEFAULT_SIZE, 852, Short.MAX_VALUE))
            .addGroup(jLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPaneLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jLayeredPaneLayout.setVerticalGroup(
            jLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelConfig, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
            .addGroup(jLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelSplash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelWorld, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelStadistics, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE))
            .addGroup(jLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelMarker, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelPolyline, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE))
            .addGroup(jLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPaneLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(jLayeredPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 750, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private int x;
    private int y;
    private void jPanelTopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTopMousePressed
        // Reiniciar la posicion x y al hacer click
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanelTopMousePressed

    private void jPanelTopMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTopMouseDragged
        // actualiza x y al hacer arrastrar
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_jPanelTopMouseDragged

    private void jPanelBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBMouseEntered
        evt.getComponent().setBackground(new java.awt.Color(55, 55, 55));
    }//GEN-LAST:event_jPanelBMouseEntered

    private void jPanelBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBMouseExited
        evt.getComponent().setBackground(new java.awt.Color(33, 33, 33));
    }//GEN-LAST:event_jPanelBMouseExited

    private void jPanelBMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBMousePressed
        evt.getComponent().setBackground(new java.awt.Color(77, 77, 77));
    }//GEN-LAST:event_jPanelBMousePressed

    private void jPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMouseReleased
        evt.getComponent().setBackground(new java.awt.Color(55, 55, 55));

        JPanel jPanel = (JPanel) evt.getSource(); //TODO
        ocultarPaneles();
        if (jPanel == jPanelBUser) {
            jLabelTitulo.setText(TITLE_USER);
            this.jPanelUser.setVisible(true);
            this.jLayeredPane.moveToFront(jPanelUser);

        } else if (jPanel == jPanelBWorld) {
            jLabelTitulo.setText(TITLE_WORLD);
            this.jPanelWorld.setVisible(true);
            this.jLayeredPane.moveToFront(jPanelWorld);

        } else if (jPanel == jPanelBConfig) {
            jLabelTitulo.setText(TITLE_CONFIG);
            this.jPanelConfig.setVisible(true);
            this.jLayeredPane.moveToFront(jPanelConfig);

        } else if (jPanel == jPanelBStatistic) {
            jLabelTitulo.setText(TITLE_STADISTIC);
            this.jPanelStadistics.setVisible(true);
            this.jLayeredPane.moveToFront(jPanelStadistics);

        } else if (jPanel == jPanelBMarker) {
            jLabelTitulo.setText(TITLE_MARKER);
            this.jPanelMarker.setVisible(true);
            this.jLayeredPane.moveToFront(jPanelMarker);

        } else if (jPanel == jPanelBPolyLine) {
            jLabelTitulo.setText(TITLE_ROUTE);
            this.jPanelPolyline.setVisible(true);
            this.jLayeredPane.moveToFront(jPanelPolyline);
        }
    }//GEN-LAST:event_jPanelMouseReleased

    private void ocultarPaneles(){
        this.jPanelSplash.setVisible(false);
        this.jPanelWorld.setVisible(false);
        this.jPanelConfig.setVisible(false);
        this.jPanelStadistics.setVisible(false);
        this.jPanelMarker.setVisible(false);
        this.jPanelPolyline.setVisible(false);
        this.jPanelUser.setVisible(false);
    }
    
    private void jLabelIconoMinimizarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoMinimizarMouseReleased
        // Minimiza la app
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jLabelIconoMinimizarMouseReleased

    private void jLabelIconoCerrarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoCerrarMouseReleased
        // Cierra la app
        System.exit(0);
    }//GEN-LAST:event_jLabelIconoCerrarMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonPolySearch;
    private javax.swing.JButton jButtonSearchUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelIconoCerrar;
    private javax.swing.JLabel jLabelIconoMinimizar;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelPic1;
    private javax.swing.JLabel jLabelPic2;
    private javax.swing.JLabel jLabelPic3;
    private javax.swing.JLabel jLabelPic4;
    private javax.swing.JLabel jLabelPolyInfoServer;
    private javax.swing.JLabel jLabelSearch;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTotalMessageStatistics;
    private javax.swing.JLabel jLabelTotalUserStatistics;
    private javax.swing.JLabel jLabelUserInfoEmail;
    private javax.swing.JLabel jLabelUserInfoName;
    private javax.swing.JLabel jLabelUserInfoTotalMessages;
    private javax.swing.JLabel jLabelUserInfoType;
    private javax.swing.JLabel jLabelUserServerInfo;
    private javax.swing.JLabel jLabelmail;
    private javax.swing.JLayeredPane jLayeredPane;
    private javax.swing.JPanel jPanelBConfig;
    private javax.swing.JPanel jPanelBMarker;
    private javax.swing.JPanel jPanelBPolyLine;
    private javax.swing.JPanel jPanelBStatistic;
    private javax.swing.JPanel jPanelBUser;
    private javax.swing.JPanel jPanelBWorld;
    private javax.swing.JPanel jPanelConfig;
    private javax.swing.JPanel jPanelLateral;
    private javax.swing.JPanel jPanelMarker;
    private javax.swing.JPanel jPanelPolyLineMap;
    private javax.swing.JPanel jPanelPolyline;
    private javax.swing.JPanel jPanelSplash;
    private javax.swing.JPanel jPanelStadistics;
    private javax.swing.JPanel jPanelSup;
    private javax.swing.JPanel jPanelTop;
    private javax.swing.JPanel jPanelUser;
    private javax.swing.JPanel jPanelUserInfo;
    private javax.swing.JPanel jPanelWorld;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextArea jTextAreaUserMessages;
    private javax.swing.JTextField jTextFieldPoly;
    private javax.swing.JTextField jTextFieldSearchUser;
    private javax.swing.JToggleButton jToggleButtonBanUser;
    private javax.swing.JLabel jlabelUser;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getjButtonLogout() {
        return jButtonLogout;
    }

    public javax.swing.JPanel getjPanelBWorld() {
        return jPanelBWorld;
    }

    public javax.swing.JPanel getjPanelWorld() {
        return jPanelWorld;
    }

    public javax.swing.JPanel getjPanelBConfig() {
        return jPanelBConfig;
    }

    public javax.swing.JPanel getjPanelBMarker() {
        return jPanelBMarker;
    }

    public javax.swing.JPanel getjPanelBStatistic() {
        return jPanelBStatistic;
    }

    public javax.swing.JPanel getjPanelBUser() {
        return jPanelBUser;
    }

    public javax.swing.JPanel getjPanelConfig() {
        return jPanelConfig;
    }

    public javax.swing.JPanel getjPanelMarker() {
        return jPanelMarker;
    }

    public javax.swing.JPanel getjPanelStadistics() {
        return jPanelStadistics;
    }
    
    public javax.swing.JPanel getjPanelUser() {
        return jPanelUser;
    }

    public javax.swing.JLabel getjLabelmail() {
        return jLabelmail;
    }

    public javax.swing.JLabel getJlabelUser() {
        return jlabelUser;
    }

    public void setJlabelUser(javax.swing.JLabel jlabelUser) {
        this.jlabelUser = jlabelUser;
    }

    public javax.swing.JPanel getjPanelBPolyLine() {
        return jPanelBPolyLine;
    }

    public javax.swing.JLabel getjLabelTotalMessageStatistics() {
        return jLabelTotalMessageStatistics;
    }

    public javax.swing.JLabel getjLabelTotalUserStatistics() {
        return jLabelTotalUserStatistics;
    }

    public javax.swing.JButton getjButtonSearchUser() {
        return jButtonSearchUser;
    }

    public javax.swing.JLabel getjLabelUserInfoEmail() {
        return jLabelUserInfoEmail;
    }

    public javax.swing.JLabel getjLabelUserInfoName() {
        return jLabelUserInfoName;
    }

    public javax.swing.JLabel getjLabelUserInfoTotalMessages() {
        return jLabelUserInfoTotalMessages;
    }

    public javax.swing.JLabel getjLabelUserInfoType() {
        return jLabelUserInfoType;
    }

    public javax.swing.JLabel getjLabelUserServerInfo() {
        return jLabelUserServerInfo;
    }

    public javax.swing.JPanel getjPanelUserInfo() {
        return jPanelUserInfo;
    }

    public javax.swing.JTextField getjTextFieldSearchUser() {
        return jTextFieldSearchUser;
    }

    public javax.swing.JToggleButton getjToggleButtonBanUser() {
        return jToggleButtonBanUser;
    }

    public javax.swing.JTextArea getjTextAreaUserMessages() {
        return jTextAreaUserMessages;
    }

    public javax.swing.JPanel getjPanelPolyLine() {
        return jPanelPolyline;
    }

    public javax.swing.JLabel[] getjLabelPics() {
        return new javax.swing.JLabel[]{jLabelPic1, jLabelPic2, jLabelPic3, jLabelPic4};
    }

    public javax.swing.JButton getjButtonPolySearch() {
        return jButtonPolySearch;
    }

    public javax.swing.JLabel getjLabelPolyInfoServer() {
        return jLabelPolyInfoServer;
    }

    public javax.swing.JTextField getjTextFieldPoly() {
        return jTextFieldPoly;
    }

    public void setjPanelPolyline(javax.swing.JPanel jPanelPolyline) {
        this.jPanelPolyline = jPanelPolyline;
    }

    public javax.swing.JPanel getjPanelPolyLineMap() {
        return jPanelPolyLineMap;
    }

    
}
